# These are supported funding model platforms

# github: [your-github-username] # GitHub Sponsors
# patreon: [your-patreon-username]
# open_collective: [your-collective]
# ko_fi: [your-kofi-username]
# custom: ['https://www.paypal.me/yourpaypal', 'https://donate.yoursite.com']

# Uncomment and add your funding links above
# This allows contributors to support the project financially

